### ISSUE TITLE
Opposing Pokemon adjusted speed stat is reading from Your Pokemon adjusted stat

### ISSUE THREAD

**Issue by Time2Clown** [tzarii/OVA-Damage-Calculator#2]
**Issue:** The adjusted speed stat displayed to the right of the +/- modifier dropdown for the Opposing Pokemon slot reads from the speed stat displayed to the right of the +/- modifier dropdown of Your Pokmeon

**Example:** Dondozo with a Commander boost should have a speed stat of 190, but displays 309. Iron Bundle properly displays its Quark Drive boosted speed stat of 309.

![Example image](https://i.imgur.com/nJR7hGm.png)

**Comment by tzarii** [comment]
Alright, this issue should now be resolved!

**Comment by tzarii** [comment]
Alright, this issue should now be resolved!
